export const apiRoutes = {
  auth: {
    login: "Auth/Login",
    refreshToken: "Auth/RefreshTokens",
  },

  pricingSettings: {
    getGlobalPricingSettings: "PricingSettings/GetGlobalPricingSettings",
    getPricingSettings: "PricingSettings/GetPricingSettings",
    getPosPricingSettings: "PricingSettings/GetPosPricingSettings",
    editPricingSettings: "PricingSettings/EditPricingSettings",
  },
  product: {
    generateSku: "Product/GenerateSku",
    validateProductImages: "Product/ValidateProductImages",
    createProduct: "Product/CreateProduct",
    editProduct: "Product/EditProduct",
    getProducts: "Product/GetProducts",
    getInventorySummary: "Product/GetInventorySummary",
    getProductById: "Product/GetProductById",
    getProductsBySkus: "Product/GetProductsBySkus",
    exportProductsToExcel: "Product/ExportProductsToExcel",
    getInventoryReports: "Product/GetInventoryReports",
    meltProduct: "Product/MeltProduct",
    getMeltedProducts: "Product/GetMeltedProducts",
    getMeltedReports: "Product/GetMeltedReports",
    upsertSpecialPricing: "Product/UpsertSpecialPricing",
    getSpecialPricing: "Product/GetSpecialPricing",
    getBullionProducts: "Product/GetBullionProducts",
  },
  users: {
    getAllUsers: "Users/GetAllUsers",
    getAllRoles: "Users/GetAllRoles/roles",
    softDeleteUser: "Users/SoftDeleteUser",
    restoreUser: "Users/RestoreUser",
    createUser: "Users/CreateUser",
    updateUser: "Users/UpdateUser",
    getUserById: "Users/GetUserById",
    getUserInfo: "Users/getUserInfo",
    getUserStats: "Users/GetUserStats",
  },
  customers: {
    createCustomer: "Customer/CreateCustomer",
    getCustomer: "Customer/GetCustomer",
    getCustomers: "Customer/GetCustomers",
    updateCustomer: "Customer/UpdateCustomer",
    getCustomerPurhcaseHistory: "Customer/GetCustomerPurhcaseHistory",
  },
  customersReports: {
    getCustomerBaseStats: "Customer/GetCustomerBaseStats",
    getCustomerTiers: "Customer/GetCustomerTiers",
    getAtRiskCustomers: "Customer/GetAtRiskCustomers",
    getCustomerActivityStats: "Customer/GetCustomerActivityStats",
    getNewCustomersChart: "Customer/GetNewCustomersChart",
    getTopCustomersReport: "Customer/GetTopCustomersReport",
  },
  sales: {
    createSale: "Sales/CreateSale",
    getSaleById: "Sales/GetSaleById",
    getSalesList: "Sales/GetSalesList",
    getSalesInsights: "Sales/GetSalesInsights",
    getSoldItems: "Sales/GetSoldItems",
    getTodaySalesSummary: "Sales/GetTodaySalesSummary",
    searchSales: "Sales/SearchSales",
    getTopCustomers: "Sales/GetTopCustomers",
  },
  returns: {
    createReturn: "Returns/CreateReturn",
    getReturnItems: "Returns/GetReturnItems",
    getReturnItemsCounts: "Returns/GetReturnItemsCounts",
    markReturnItemsPrinted: "Returns/MarkReturnItemsPrinted",
  },
  repairs: {
    createRepair: "Repairs/CreateRepair",
    getRepairs: "Repairs/GetRepairs",
    getNextAvailableSlot: "Repairs/GetNextAvailableSlot",
    getRepairById: "Repairs/GetRepairById",
    updateRepairStatus: "Repairs/UpdateRepairStatus",
    updateRepairPaymentStatus: "Repairs/UpdateRepairPaymentStatus",
    updateRepair: "Repairs/UpdateRepair",
  },
  repairsReports: {
    getRepairsStats: "Repairs/GetRepairsStats",
    getRepairHealthMetrics: "Repairs/GetRepairHealthMetrics",
    getRepairAlerts: "Repairs/GetRepairAlerts",
    getRepairsRevenueChart: "Repairs/GetRepairsRevenueChart",
    getRepairsByCustomer: "Repairs/GetRepairsByCustomer",
    getAvgRepairValueHistory: "Repairs/GetAvgRepairValueHistory",
    getRepeatCustomers: "Repairs/GetRepeatCustomers",
    getLongestInShop: "Repairs/GetLongestInShop",
  },
  analytics: {
    getSalesOverTime: "Analytics/GetSalesOverTime",
    getSalesByCategory: "Analytics/GetSalesByCategory",
    getStaffPerformance: "Analytics/GetStaffPerformance",
    getAnalyticsSummary: "Analytics/GetAnalyticsSummary",
    getPriceOverTime: "Analytics/GetPriceOverTime",
    getCustomerRetention: "Analytics/GetCustomerRetention",
  },
  inventoryReports: {
    getInventoryAging: "Analytics/GetInventoryAging",
    getInventoryStockSummary: "Analytics/GetInventoryStockSummary",
    getStockByPurity: "Analytics/GetStockByPurity",
    getStockByCategory: "Analytics/GetStockByCategory",
    getInventoryMovement: "Analytics/GetInventoryMovement",
    getMovementByPurity: "Analytics/GetMovementByPurity",
    getStaplesSold: "Analytics/GetStaplesSold",
  },
  logs: {
    getLogs: "Logs/GetLogs",
    deleteLogs: "Logs/DeleteLogs",
  },
  cashManagement: {
    getCashBalances: "CashManagement/GetCashBalances",
    getCashTransactions: "CashManagement/GetCashTransactions",
    addExpense: "CashManagement/AddExpense",
    manualCashIn: "CashManagement/ManualCashIn",
    transferIncome: "CashManagement/TransferIncome",
    moveMoney: "CashManagement/MoveMoney",
  },
  usedGold: {
    createPurchase: "UsedGold/CreatePurchase",
    getPools: "UsedGold/GetPools",
    getHistory: "UsedGold/GetHistory",
    sendToMelt: "UsedGold/SendToMelt",
    returnToStock: "UsedGold/ReturnToStock",
    getSummary: "UsedGold/GetSummary",
  },
  securitySettings: {
    getSalesPin: "SecuritySettings/GetSalesPin",
    updateSalesPin: "SecuritySettings/UpdateSalesPin",
    verifySalesPin: "SecuritySettings/VerifySalesPin",
  },
  inventorySettings: {
    getLowStockThreshold: "InventorySettings/GetLowStockThreshold",
    updateLowStockThreshold: "InventorySettings/UpdateLowStockThreshold",
  },
  dashboard: {
    getPosDashboardStats: "Dashboard/GetPosDashboardStats",
    getAdminSalesSummary: "Dashboard/GetAdminSalesSummary",
    getAdminCashGoldSnapshot: "Dashboard/GetAdminCashGoldSnapshot",
    getAdminRepairsStats: "Dashboard/GetAdminRepairsStats",
    getAdminInventorySnapshot: "Dashboard/GetAdminInventorySnapshot",
    getAdminAttentionItems: "Dashboard/GetAdminAttentionItems",
  },
  printJobs: {
    createReceiptPrintJob: "PrintJobs/CreateReceiptPrintJob",
    claimNextPrintJob: "PrintJobs/ClaimNextPrintJob",
    markPrintJobStarted: "PrintJobs/MarkPrintJobStarted",
    markPrintJobSucceeded: "PrintJobs/MarkPrintJobSucceeded",
    markPrintJobFailed: "PrintJobs/MarkPrintJobFailed",
  },
};
