export const apiRoutes = {
  auth: {
    login: "Auth/Login",
    refreshToken: "Auth/RefreshTokens",
  },
  cart: {
    addProductToCart: "Cart/AddProductToCart",
    getCartProducts: "Cart/GetCartProducts",
    deleteCart: "Cart/DeleteCart",
    removeProductFromCart: "Cart/RemoveProductFromCart",
  },
  pricingSettings: {
    getGlobalPricingSettings: "PricingSettings/GetGlobalPricingSettings",
    getPricingSettings: "PricingSettings/GetPricingSettings",
    editPricingSettings: "PricingSettings/EditPricingSettings",
  },
  product: {
    generateSku: "Product/GenerateSku",
    validateProductImages: "Product/ValidateProductImages",
    createProduct: "Product/CreateProduct",
    editProduct: "Product/EditProduct",
    getProducts: "Product/GetProducts",
    deleteProduct: "Product/DeleteProduct",
    getProductById: "Product/GetProductById",
    getProductsBySkus: "Product/GetProductsBySkus",
  },
  users: {
    getAllUsers: "Users/GetAllUsers",
    getAllRoles: "Users/GetAllRoles/roles",
    softDeleteUser: "Users/SoftDeleteUser",
    createUser: "Users/CreateUser",
    updateUser: "Users/UpdateUser",
    getUserById: "Users/GetUserById",
    getUserInfo: "Users/getUserInfo",
  },
  customers: {
    createCustomer: "Customer/CreateCustomer",
    getCustomer: "Customer/GetCustomer",
    getCustomers: "Customer/GetCustomers",
    deleteCustomer: "Customer/DeleteCustomer",
    updateCustomer: "Customer/UpdateCustomer",
    getCustomerPurhcaseHistory: "Customer/GetCustomerPurhcaseHistory",
  },
  sales: {
    createSale: "Sales/CreateSale",
    getSaleById: "Sales/GetSaleById",
    getSalesList: "Sales/GetSalesList",
    getSalesInsights: "Sales/GetSalesInsights",
    getSoldItems: "Sales/GetSoldItems",
    getSalesCustomers: "Sales/GetSalesCustomers",
    getDashboardInsights: "Sales/GetDashboardInsights",
    getTopSellingCategories: "Sales/GetTopSellingCategories",
  },
  returns: {
    createReturn: "Returns/CreateReturn",
  },
  repairs: {
    createRepair: "Repairs/CreateRepair",
    getRepairs: "Repairs/GetRepairs",
    getRepairById: "Repairs/GetRepairById",
    updateRepairStatus: "Repairs/UpdateRepairStatus",
    updateRepair: "Repairs/UpdateRepair",
    getRepairAnalytics: "Repairs/GetRepairAnalytics",
  },
  analytics: {
    getSalesOverTime: "Analytics/GetSalesOverTime",
    getSalesByCategory: "Analytics/GetSalesByCategory",
    getStaffPerformance: "Analytics/GetStaffPerformance",
    getAnalyticsSummary: "Analytics/GetAnalyticsSummary",
  },
  logs: {
    getLogs: "Logs/GetLogs",
    deleteLogs: "Logs/DeleteLogs",
  },
};
