<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\images\products\18K\**" />
    <Compile Remove="wwwroot\images\products\21K\**" />
    <Content Remove="wwwroot\images\products\18K\**" />
    <Content Remove="wwwroot\images\products\21K\**" />
    <EmbeddedResource Remove="wwwroot\images\products\18K\**" />
    <EmbeddedResource Remove="wwwroot\images\products\21K\**" />
    <None Remove="wwwroot\images\products\18K\**" />
    <None Remove="wwwroot\images\products\21K\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JewerlyApp.Application\JewerlyApp.Application.csproj" />
    <ProjectReference Include="..\JewerlyApp.Infrastructure\JewerlyApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\products\" />
  </ItemGroup>

</Project>
