name: Deploy DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy To Server Via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "== Pull latest code =="
            cd /var/www/jewelryApp-dev
            git reset --hard
            git pull

            echo "== Apply migrations =="
            cd src/JewerlyApp.API
            dotnet ef database update \
              --project ../JewerlyApp.Infrastructure/ \
              --startup-project . \
              --connection "${{ secrets.DB_CONNECTION_STRING_DEV }}"

            echo "== Publish backend =="
            dotnet publish -c Release -o /var/www/jewelryApp-dev/src/JewerlyApp.API/publish/ --self-contained false

            echo "== Restart backend service =="
            sudo systemctl restart jewelryApp-dev

            echo "== Build frontend =="
            cd /var/www/jewelryApp-dev/JewelryApp.UI
            
            # Clean old environment
            rm -rf node_modules dist
            
            echo "== Install dependencies =="
            npm ci

            echo "== Type-check (TS errors will stop pipeline) =="
            npx tsc --noEmit --pretty

            echo "== Frontend build =="
            npm run build:dev

            echo "== DONE DEPLOYMENT ✔ =="
